### ISSUE TITLE
Tagging a release

### ISSUE THREAD

**Issue by williamboman** [ChristianChiarulli/colorgen-nvim#9]
Hey 👋! I'm currently migrating package definitions from [mason.nvim](https://github.com/williamboman/mason.nvim) to versioned YAML-based definitions in https://github.com/mason-org/mason-registry. A new constraint that has been introduced is that packages must provide some kind of versioning mechanism, which this package doesn't yet fulfil.

For Cargo based packages, this can either be via the default crates.io repository, or via git tags if hosted via GitHub repositories. Seeing as this package is a git-based Cargo package - would you mind tagging an initial version in these trying times 🙏? Any git tag would do (although preferably semver for better portability).

**Comment by ChristianChiarulli** [comment]
Sure, no problem. I probably should've tagged a release a while ago anyway. Thanks for including the project in mason.
